/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as StaffAccessHerNamibiaRouteImport } from './routes/staff-access-her-namibia'
import { Route as AuthenticatedHerNamibiaAdminRouteImport } from './routes/_authenticated/HerNamibia-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAccessHerNamibiaRoute = StaffAccessHerNamibiaRouteImport.update({
  id: '/staff-access-her-namibia',
  path: '/staff-access-her-namibia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHerNamibiaAdminRoute =
  AuthenticatedHerNamibiaAdminRouteImport.update({
    id: '/HerNamibia-admin',
    path: '/HerNamibia-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/podcast': typeof PodcastRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/staff-access-her-namibia': typeof StaffAccessHerNamibiaRoute
  '/HerNamibia-admin': typeof AuthenticatedHerNamibiaAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/podcast': typeof PodcastRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/staff-access-her-namibia': typeof StaffAccessHerNamibiaRoute
  '/HerNamibia-admin': typeof AuthenticatedHerNamibiaAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/news': typeof NewsRoute
  '/podcast': typeof PodcastRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/staff-access-her-namibia': typeof StaffAccessHerNamibiaRoute
  '/_authenticated/HerNamibia-admin': typeof AuthenticatedHerNamibiaAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/news'
    | '/podcast'
    | '/projects'
    | '/resources'
    | '/staff-access-her-namibia'
    | '/HerNamibia-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/news'
    | '/podcast'
    | '/projects'
    | '/resources'
    | '/staff-access-her-namibia'
    | '/HerNamibia-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/news'
    | '/podcast'
    | '/projects'
    | '/resources'
    | '/staff-access-her-namibia'
    | '/_authenticated/HerNamibia-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  NewsRoute: typeof NewsRoute
  PodcastRoute: typeof PodcastRoute
  ProjectsRoute: typeof ProjectsRoute
  ResourcesRoute: typeof ResourcesRoute
  StaffAccessHerNamibiaRoute: typeof StaffAccessHerNamibiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-access-her-namibia': {
      id: '/staff-access-her-namibia'
      path: '/staff-access-her-namibia'
      fullPath: '/staff-access-her-namibia'
      preLoaderRoute: typeof StaffAccessHerNamibiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/HerNamibia-admin': {
      id: '/_authenticated/HerNamibia-admin'
      path: '/HerNamibia-admin'
      fullPath: '/HerNamibia-admin'
      preLoaderRoute: typeof AuthenticatedHerNamibiaAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHerNamibiaAdminRoute: typeof AuthenticatedHerNamibiaAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHerNamibiaAdminRoute: AuthenticatedHerNamibiaAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  NewsRoute: NewsRoute,
  PodcastRoute: PodcastRoute,
  ProjectsRoute: ProjectsRoute,
  ResourcesRoute: ResourcesRoute,
  StaffAccessHerNamibiaRoute: StaffAccessHerNamibiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
